### ISSUE TITLE
Request for original drone image data

### ISSUE THREAD

**Issue by zhouyuxiang1027** [UTokyo-FieldPhenomics-Lab/UAVbroccoli#1]
Thank you for your share!

Your research is so interesting!
I would like to kindly request access to this dataset, if possible.

Thank you very much for considering my request. I look forward to your positive response.

**Comment by HowcanoeWang** [comment]
Apologies for this late reply. We just finished organzing demo dataset, to minimize the file sizes for easier downloading.

Later, we will share you a link to a google form, after filling some information, it would give you the download link to demo dataset. 

It is recommended to use 2022 data to start up, well organized and passed by metashape, whose scripts are shared in the repo.

**Comment by zhouyuxiang1027** [comment]
Your response is greatly appreciated. Thank you for your help.

**Comment by HowcanoeWang** [comment]
We have just passed the test for google form and email notification, please help us test if [this form link](https://forms.gle/pLRRf7Ye9nhVX31f7) works or not

**Comment by zhouyuxiang1027** [comment]
Thank you for your help.

When the google form link was clicked, [You need permissions
Only users in the organization of the form owner can view the form.] was shown.

**Comment by HowcanoeWang** [comment]
@zhouyuxiang1027 should be fixed now

**Comment by zhouyuxiang1027** [comment]
Thank you so much! It was very helpful.
